/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUpcomingBookingsRouteImport } from './routes/api/upcoming-bookings'
import { Route as ApiRecentActionsRouteImport } from './routes/api/recent-actions'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiConnectionStatusRouteImport } from './routes/api/connection-status'
import { Route as ApiClearFeedRouteImport } from './routes/api/clear-feed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpcomingBookingsRoute = ApiUpcomingBookingsRouteImport.update({
  id: '/api/upcoming-bookings',
  path: '/api/upcoming-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecentActionsRoute = ApiRecentActionsRouteImport.update({
  id: '/api/recent-actions',
  path: '/api/recent-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionStatusRoute = ApiConnectionStatusRouteImport.update({
  id: '/api/connection-status',
  path: '/api/connection-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearFeedRoute = ApiClearFeedRouteImport.update({
  id: '/api/clear-feed',
  path: '/api/clear-feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/clear-feed': typeof ApiClearFeedRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recent-actions': typeof ApiRecentActionsRoute
  '/api/upcoming-bookings': typeof ApiUpcomingBookingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/clear-feed': typeof ApiClearFeedRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recent-actions': typeof ApiRecentActionsRoute
  '/api/upcoming-bookings': typeof ApiUpcomingBookingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/clear-feed': typeof ApiClearFeedRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recent-actions': typeof ApiRecentActionsRoute
  '/api/upcoming-bookings': typeof ApiUpcomingBookingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/clear-feed'
    | '/api/connection-status'
    | '/api/health'
    | '/api/recent-actions'
    | '/api/upcoming-bookings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/clear-feed'
    | '/api/connection-status'
    | '/api/health'
    | '/api/recent-actions'
    | '/api/upcoming-bookings'
  id:
    | '__root__'
    | '/'
    | '/api/clear-feed'
    | '/api/connection-status'
    | '/api/health'
    | '/api/recent-actions'
    | '/api/upcoming-bookings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiClearFeedRoute: typeof ApiClearFeedRoute
  ApiConnectionStatusRoute: typeof ApiConnectionStatusRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRecentActionsRoute: typeof ApiRecentActionsRoute
  ApiUpcomingBookingsRoute: typeof ApiUpcomingBookingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upcoming-bookings': {
      id: '/api/upcoming-bookings'
      path: '/api/upcoming-bookings'
      fullPath: '/api/upcoming-bookings'
      preLoaderRoute: typeof ApiUpcomingBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recent-actions': {
      id: '/api/recent-actions'
      path: '/api/recent-actions'
      fullPath: '/api/recent-actions'
      preLoaderRoute: typeof ApiRecentActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connection-status': {
      id: '/api/connection-status'
      path: '/api/connection-status'
      fullPath: '/api/connection-status'
      preLoaderRoute: typeof ApiConnectionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clear-feed': {
      id: '/api/clear-feed'
      path: '/api/clear-feed'
      fullPath: '/api/clear-feed'
      preLoaderRoute: typeof ApiClearFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiClearFeedRoute: ApiClearFeedRoute,
  ApiConnectionStatusRoute: ApiConnectionStatusRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRecentActionsRoute: ApiRecentActionsRoute,
  ApiUpcomingBookingsRoute: ApiUpcomingBookingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
